import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import fs from 'node:fs';
import path from 'node:path';

/**
 * Dev-only watchdog logger.
 * The chaos monitor runs in the browser and can't touch the filesystem, so it
 * POSTs each new violation to `/__watchdog`. This middleware appends them to
 * `playtest-log.md` in the project root for an agent (or you) to read later.
 */
function watchdogLogger(): Plugin {
  const logPath = path.resolve(process.cwd(), 'playtest-log.md');

  function ensureHeader(): void {
    if (!fs.existsSync(logPath)) {
      fs.writeFileSync(
        logPath,
        '# Costco Chaos — Playtest Watchdog Log\n\n' +
          '_Auto-generated by the dev server. Each session appends below._\n',
      );
    }
  }

  return {
    name: 'costco-watchdog-logger',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/__watchdog', (req, res) => {
        if (req.method !== 'POST') {
          res.statusCode = 405;
          res.end();
          return;
        }

        let body = '';
        req.on('data', (chunk) => {
          body += chunk;
        });
        req.on('end', () => {
          try {
            const data = JSON.parse(body || '{}');
            ensureHeader();

            let line = '';
            if (data.type === 'session') {
              const ts = new Date(data.at ?? Date.now()).toLocaleString();
              const label = data.label ? ` — ${data.label}` : '';
              line = `\n## Session ${ts}${label}\n\n`;
            } else if (data.type === 'violation') {
              const ts = new Date(data.at ?? Date.now()).toLocaleTimeString();
              line = `- \`${data.kind}\` ${data.message}  _(${ts})_\n`;
            } else if (data.type === 'note') {
              line = `> ${data.message}\n`;
            }

            if (line) fs.appendFileSync(logPath, line);
            res.statusCode = 204;
            res.end();
          } catch {
            res.statusCode = 400;
            res.end();
          }
        });
      });
    },
  };
}

export default defineConfig({
  base: '/costco-chaos/',
  plugins: [react(), watchdogLogger()],
  server: {
    port: 5173,
    strictPort: true,
    proxy: {
      // Forward /api/* to the Node dev proxy (scripts/dev-proxy.js)
      '/api': {
        target: 'http://localhost:8081',
        changeOrigin: true,
      },
    },
  },
});
